name: Build and Deploy to Cloud Run

on:
    pull_request:
        types: [synchronize, opened, reopened, closed]

env:
    PROJECT: "floatcast-dev"
    HOSTNAME: "gcr.io"
    REGION: "asia-northeast1"
    SERVICE: preview-${{ github.event.number }}
    GCP_SA_KEY_DEV: ${{ secrets.GCP_SA_KEY_DEV }}

jobs:
    setup-build-publish-deploy:
        name: Setup, Build, Publish and Deploy
        if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                service_account_key: ${GCP_SA_KEY_DEV}
                project_id: ${PROJECT}
                export_default_credentials: true
            
            - name: Configure Docker
              run: gcloud auth configure-docker --quiet
           
            - name: Build
              run: |
                docker build -t ${HOSTNAME}/${PROJECT}-api-${SERVICE}:${GITHUB_SHA:0:8} /api
            
            - name: Publish
              run: |
                docker push ${HOSTNAME}/${PROJECT}-api-${SERVICE}:${GITHUB_SHA:0:8}
            
            - name: Deploy
              run: |
                gcloud run deploy api-${SERVICE} \
                    --image ${HOSTNAME}/${PROJECT}-api-${SERVICE}:${GITHUB_SHA:0:8}
                PREVIEW_URL=$(gcloud run services describe api-${SERVICE} --format 'value(status.url)')
                gcloud run services update api-${SERVICE} --set-env-vars BASE_URL=${PREVIEW_URL}

            - name: Notify
              run: |
                PREVIEW_URL=$(gcloud run services describe api-${SERVICE} --format 'value(status.url)')
                gh pr comment -F ./comments "Preview URL: ${PREVIEW_URL}"